#pragma once

void numpy_array_exceptions_fn();